FROM ubuntu:latest

RUN apt-get update
RUN apt-get -y upgrade

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install apache2 curl

# Enable apache mods.
RUN a2enmod ssl proxy proxy_wstunnel proxy_http rewrite

# Manually set up the apache environment variables
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

EXPOSE 80
EXPOSE 443

ADD ./html /var/www/html

# Update the default apache site with the config we created.
ADD ./site-configs/example.com/example.conf /etc/apache2/sites-enabled/example.conf
ADD ./site-configs/example.com/example-SSL.conf /etc/apache2/sites-enabled/example-SSL.conf

# By default, simply start apache.
CMD /usr/sbin/apache2ctl -D FOREGROUND
