FROM golang as build-stage
WORKDIR /opt/app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o binary

FROM alpine AS build-release-stage
WORKDIR /opt/app
COPY --from=build-stage /opt/app/binary /opt/app/binary

EXPOSE 80

USER 1000:1000

ENTRYPOINT ["/opt/app/binary"]
CMD ["/opt/app/binary"]