FROM node:16 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .

RUN npm run build

#serve static html using caddy
FROM caddy
COPY --from=build /app/dist/app /srv/html/
COPY ./Caddyfile /etc/caddy/Caddyfile
EXPOSE 80
